### ISSUE TITLE
Backslash-Error bei writeCustomChar

### ISSUE THREAD

**Issue by MKleinSB** [Banbury/pxt-calliope-oled96#5]
Hallo banbury,
Ich habe dein Superpaket um Sonderzeichen ergänzt und bin dabei auf ein Problem mit writeCustomChar gestoßen:
Wenn man den String in den Block eingibt und compiliert entsteht nur Grafikmüll.
![1](https://user-images.githubusercontent.com/37311672/63101551-939d0500-bf79-11e9-8668-9acdd98642c1.png)

Beim Wechsel auf Javascript stößt man auf den Fehler, der aber wohl an MakeCode liegt:
![2](https://user-images.githubusercontent.com/37311672/63101559-97c92280-bf79-11e9-9073-09710ce41112.png)

Der Backslash wird verdoppelt.

**Comment by Banbury** [comment]
Ich glaube nicht, dass ich da was machen kann. Das ist ein Problem des Konverters, der übereifrig ein Escape-Zeichen einfügt.

**Comment by MKleinSB** [comment]
Danke, habe ich mir gedacht, hatte noch etwas herumexperimentiert. Bleibt man besser in Javascript bei eigenen Zeichen.
